baseURL = 'https://Tallisgo.github.io/'
languageCode = 'zh-cn'
title = 'Tallis'
theme = 'PaperMod'

[params]
  env = 'production'
  title = 'Tallis Blog'
  description = '我的个人博客'
  keywords = ["Blog", "Hugo", "PaperMod"]
  author = 'Tallis'
  
  # 搜索配置
  search = true
  searchPage = true
  
  # 搜索选项配置
  [params.fuseOpts]
    iscasesensitive = false
    includescore = false
    includematches = false
    minmatchcharlength = 1
    shouldsort = true
    findallmatches = false
    location = 0
    threshold = 0.4
    distance = 100
    ignorelocation = true
    limit = 10
    keys = ["title", "permalink", "summary", "content"]
  
  # 主题配置
  defaultTheme = 'light'
  disableThemeToggle = false
  
  # 显示配置
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false


[menu]
  [[menu.main]]
    identifier = 'home'
    name = '首页'
    url = '/'
    weight = 10
  
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 20
  
  [[menu.main]]
    identifier = 'tags'
    name = '标签'
    url = '/tags/'
    weight = 30

  [[menu.main]]
    identifier = 'search'
    name = '搜索'
    url = '/search/'
    weight = 40

# 输出格式配置
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[outputFormats]
  [outputFormats.JSON]
    baseName = "index"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = 'github'
